# username/repository
id: widepay/api

# name of the software
name: Wide Pay API

# current version of the software
version:

# extension of the favicon, blank to disable
favicon: png

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/widepay
  - title: Wide Pay
    url: https://www.widepay.com

# header
header:
  color1: "#111111"
  color2: "#7dcf45"
  trianglify: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from