# username/repository
id: widepay/api

# name of the software
name: Wide Pay API

# current version of the software
version:

# extension of the favicon, blank to disable
favicon: png

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/widepay
  - title: Slack
    url: https://join.slack.com/t/widepay/shared_invite/enQtNTgxOTgyMTI5OTg3LTkyZDJkZDA0Yjc0NzQ0MTRhZmEwYTA3NDliY2QwMmY1NmM2MmNhMmI2OTU5ZTg0NmZlMTQ1MjhjODk4NGNkN2U
  - title: Wide Pay
    url: https://www.widepay.com

# header
header:
  color1: "#111111"
  color2: "#7dcf45"
  trianglify: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
