# username/repository
id: widepay/api
# name of the software
name: Wide Pay API
# current version of the software
version: 1.0.0
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT
# extension of the favicon, blank to disable
favicon: png

# download button
# if download.popup is true, the download button will open a popup with several download options
# otherwise it will simply open download.url and other options are ignored
# if download.popup is true, any option is optional
# download.cdn.img is optional
download:
  popup: false
  url:
  bower:
  npm:
  cdn:
    url:
    img:
    name:

# set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: false

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/widepay
  - title: Wide Pay
    url: https://www.widepay.com

# list if additional links on the footer
footerLinks:
  - title:
    url:

# header
header:
  color1: "#000000"
  color2: "#7db458"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user:
  repo:

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:


exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
